//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::robot_cubes::Entity as RobotCubes;
pub use super::robot_metadata::Entity as RobotMetadata;
//pub use super::state::Entity as State;
