//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ROBOT_CUBES")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: u32,
    #[sea_orm(column_type = "Text")]
    pub cube_data: String,
    #[sea_orm(column_type = "Text")]
    pub colour_data: String,
    #[sea_orm(column_type = "Text")]
    pub cube_amounts: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
