//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, DeriveEntityModel)]
#[sea_orm(table_name = "ROBOT_METADATA")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: u32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub thumbnail: String,
    #[sea_orm(column_type = "Text")]
    pub added_by: String,
    #[sea_orm(column_type = "Text")]
    pub added_by_display_name: String,
    #[sea_orm(column_type = "Text")]
    pub added_date: String,
    #[sea_orm(column_type = "Text")]
    pub expiry_date: String,
    pub cpu: u32,
    pub total_robot_ranking: i32,
    pub rent_count: i32,
    pub buy_count: i32,
    pub buyable: i32,
    pub featured: i32,
    #[sea_orm(column_type = "Float")]
    pub combat_rating: f64,
    #[sea_orm(column_type = "Float")]
    pub cosmetic_rating: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
